// Get each div:
const div1 = document.getElementById('1');
const div2 = document.getElementById('2');
const div3 = document.getElementById('3');
const div4 = document.getElementById('4');
const div5 = document.getElementById('5');
const div6 = document.getElementById('6');
const div7 = document.getElementById('7');
const div8 = document.getElementById('8');
const div9 = document.getElementById('9'); 